// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api_server/ent/configuration"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfigurationCreate is the builder for creating a Configuration entity.
type ConfigurationCreate struct {
	config
	mutation *ConfigurationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConfigType sets the "config_type" field.
func (cc *ConfigurationCreate) SetConfigType(s string) *ConfigurationCreate {
	cc.mutation.SetConfigType(s)
	return cc
}

// SetConfigKey sets the "config_key" field.
func (cc *ConfigurationCreate) SetConfigKey(s string) *ConfigurationCreate {
	cc.mutation.SetConfigKey(s)
	return cc
}

// SetConfigVal sets the "config_val" field.
func (cc *ConfigurationCreate) SetConfigVal(s string) *ConfigurationCreate {
	cc.mutation.SetConfigVal(s)
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *ConfigurationCreate) SetCreatedAt(t time.Time) *ConfigurationCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *ConfigurationCreate) SetNillableCreatedAt(t *time.Time) *ConfigurationCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *ConfigurationCreate) SetUpdatedAt(t time.Time) *ConfigurationCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *ConfigurationCreate) SetNillableUpdatedAt(t *time.Time) *ConfigurationCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *ConfigurationCreate) SetID(i int) *ConfigurationCreate {
	cc.mutation.SetID(i)
	return cc
}

// Mutation returns the ConfigurationMutation object of the builder.
func (cc *ConfigurationCreate) Mutation() *ConfigurationMutation {
	return cc.mutation
}

// Save creates the Configuration in the database.
func (cc *ConfigurationCreate) Save(ctx context.Context) (*Configuration, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ConfigurationCreate) SaveX(ctx context.Context) *Configuration {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ConfigurationCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ConfigurationCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ConfigurationCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := configuration.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := configuration.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ConfigurationCreate) check() error {
	if _, ok := cc.mutation.ConfigType(); !ok {
		return &ValidationError{Name: "config_type", err: errors.New(`ent: missing required field "Configuration.config_type"`)}
	}
	if _, ok := cc.mutation.ConfigKey(); !ok {
		return &ValidationError{Name: "config_key", err: errors.New(`ent: missing required field "Configuration.config_key"`)}
	}
	if _, ok := cc.mutation.ConfigVal(); !ok {
		return &ValidationError{Name: "config_val", err: errors.New(`ent: missing required field "Configuration.config_val"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Configuration.created_at"`)}
	}
	return nil
}

func (cc *ConfigurationCreate) sqlSave(ctx context.Context) (*Configuration, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ConfigurationCreate) createSpec() (*Configuration, *sqlgraph.CreateSpec) {
	var (
		_node = &Configuration{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(configuration.Table, sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeInt))
	)
	_spec.OnConflict = cc.conflict
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.ConfigType(); ok {
		_spec.SetField(configuration.FieldConfigType, field.TypeString, value)
		_node.ConfigType = value
	}
	if value, ok := cc.mutation.ConfigKey(); ok {
		_spec.SetField(configuration.FieldConfigKey, field.TypeString, value)
		_node.ConfigKey = value
	}
	if value, ok := cc.mutation.ConfigVal(); ok {
		_spec.SetField(configuration.FieldConfigVal, field.TypeString, value)
		_node.ConfigVal = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(configuration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(configuration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Configuration.Create().
//		SetConfigType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConfigurationUpsert) {
//			SetConfigType(v+v).
//		}).
//		Exec(ctx)
func (cc *ConfigurationCreate) OnConflict(opts ...sql.ConflictOption) *ConfigurationUpsertOne {
	cc.conflict = opts
	return &ConfigurationUpsertOne{
		create: cc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Configuration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cc *ConfigurationCreate) OnConflictColumns(columns ...string) *ConfigurationUpsertOne {
	cc.conflict = append(cc.conflict, sql.ConflictColumns(columns...))
	return &ConfigurationUpsertOne{
		create: cc,
	}
}

type (
	// ConfigurationUpsertOne is the builder for "upsert"-ing
	//  one Configuration node.
	ConfigurationUpsertOne struct {
		create *ConfigurationCreate
	}

	// ConfigurationUpsert is the "OnConflict" setter.
	ConfigurationUpsert struct {
		*sql.UpdateSet
	}
)

// SetConfigType sets the "config_type" field.
func (u *ConfigurationUpsert) SetConfigType(v string) *ConfigurationUpsert {
	u.Set(configuration.FieldConfigType, v)
	return u
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ConfigurationUpsert) UpdateConfigType() *ConfigurationUpsert {
	u.SetExcluded(configuration.FieldConfigType)
	return u
}

// SetConfigKey sets the "config_key" field.
func (u *ConfigurationUpsert) SetConfigKey(v string) *ConfigurationUpsert {
	u.Set(configuration.FieldConfigKey, v)
	return u
}

// UpdateConfigKey sets the "config_key" field to the value that was provided on create.
func (u *ConfigurationUpsert) UpdateConfigKey() *ConfigurationUpsert {
	u.SetExcluded(configuration.FieldConfigKey)
	return u
}

// SetConfigVal sets the "config_val" field.
func (u *ConfigurationUpsert) SetConfigVal(v string) *ConfigurationUpsert {
	u.Set(configuration.FieldConfigVal, v)
	return u
}

// UpdateConfigVal sets the "config_val" field to the value that was provided on create.
func (u *ConfigurationUpsert) UpdateConfigVal() *ConfigurationUpsert {
	u.SetExcluded(configuration.FieldConfigVal)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConfigurationUpsert) SetUpdatedAt(v time.Time) *ConfigurationUpsert {
	u.Set(configuration.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConfigurationUpsert) UpdateUpdatedAt() *ConfigurationUpsert {
	u.SetExcluded(configuration.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ConfigurationUpsert) ClearUpdatedAt() *ConfigurationUpsert {
	u.SetNull(configuration.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Configuration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(configuration.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConfigurationUpsertOne) UpdateNewValues() *ConfigurationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(configuration.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(configuration.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Configuration.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConfigurationUpsertOne) Ignore() *ConfigurationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConfigurationUpsertOne) DoNothing() *ConfigurationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConfigurationCreate.OnConflict
// documentation for more info.
func (u *ConfigurationUpsertOne) Update(set func(*ConfigurationUpsert)) *ConfigurationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConfigurationUpsert{UpdateSet: update})
	}))
	return u
}

// SetConfigType sets the "config_type" field.
func (u *ConfigurationUpsertOne) SetConfigType(v string) *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetConfigType(v)
	})
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ConfigurationUpsertOne) UpdateConfigType() *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateConfigType()
	})
}

// SetConfigKey sets the "config_key" field.
func (u *ConfigurationUpsertOne) SetConfigKey(v string) *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetConfigKey(v)
	})
}

// UpdateConfigKey sets the "config_key" field to the value that was provided on create.
func (u *ConfigurationUpsertOne) UpdateConfigKey() *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateConfigKey()
	})
}

// SetConfigVal sets the "config_val" field.
func (u *ConfigurationUpsertOne) SetConfigVal(v string) *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetConfigVal(v)
	})
}

// UpdateConfigVal sets the "config_val" field to the value that was provided on create.
func (u *ConfigurationUpsertOne) UpdateConfigVal() *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateConfigVal()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConfigurationUpsertOne) SetUpdatedAt(v time.Time) *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConfigurationUpsertOne) UpdateUpdatedAt() *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ConfigurationUpsertOne) ClearUpdatedAt() *ConfigurationUpsertOne {
	return u.Update(func(s *ConfigurationUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *ConfigurationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConfigurationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConfigurationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConfigurationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConfigurationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConfigurationCreateBulk is the builder for creating many Configuration entities in bulk.
type ConfigurationCreateBulk struct {
	config
	err      error
	builders []*ConfigurationCreate
	conflict []sql.ConflictOption
}

// Save creates the Configuration entities in the database.
func (ccb *ConfigurationCreateBulk) Save(ctx context.Context) ([]*Configuration, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Configuration, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfigurationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ConfigurationCreateBulk) SaveX(ctx context.Context) []*Configuration {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ConfigurationCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ConfigurationCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Configuration.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConfigurationUpsert) {
//			SetConfigType(v+v).
//		}).
//		Exec(ctx)
func (ccb *ConfigurationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConfigurationUpsertBulk {
	ccb.conflict = opts
	return &ConfigurationUpsertBulk{
		create: ccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Configuration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ccb *ConfigurationCreateBulk) OnConflictColumns(columns ...string) *ConfigurationUpsertBulk {
	ccb.conflict = append(ccb.conflict, sql.ConflictColumns(columns...))
	return &ConfigurationUpsertBulk{
		create: ccb,
	}
}

// ConfigurationUpsertBulk is the builder for "upsert"-ing
// a bulk of Configuration nodes.
type ConfigurationUpsertBulk struct {
	create *ConfigurationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Configuration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(configuration.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConfigurationUpsertBulk) UpdateNewValues() *ConfigurationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(configuration.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(configuration.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Configuration.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConfigurationUpsertBulk) Ignore() *ConfigurationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConfigurationUpsertBulk) DoNothing() *ConfigurationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConfigurationCreateBulk.OnConflict
// documentation for more info.
func (u *ConfigurationUpsertBulk) Update(set func(*ConfigurationUpsert)) *ConfigurationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConfigurationUpsert{UpdateSet: update})
	}))
	return u
}

// SetConfigType sets the "config_type" field.
func (u *ConfigurationUpsertBulk) SetConfigType(v string) *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetConfigType(v)
	})
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ConfigurationUpsertBulk) UpdateConfigType() *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateConfigType()
	})
}

// SetConfigKey sets the "config_key" field.
func (u *ConfigurationUpsertBulk) SetConfigKey(v string) *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetConfigKey(v)
	})
}

// UpdateConfigKey sets the "config_key" field to the value that was provided on create.
func (u *ConfigurationUpsertBulk) UpdateConfigKey() *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateConfigKey()
	})
}

// SetConfigVal sets the "config_val" field.
func (u *ConfigurationUpsertBulk) SetConfigVal(v string) *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetConfigVal(v)
	})
}

// UpdateConfigVal sets the "config_val" field to the value that was provided on create.
func (u *ConfigurationUpsertBulk) UpdateConfigVal() *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateConfigVal()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConfigurationUpsertBulk) SetUpdatedAt(v time.Time) *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConfigurationUpsertBulk) UpdateUpdatedAt() *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ConfigurationUpsertBulk) ClearUpdatedAt() *ConfigurationUpsertBulk {
	return u.Update(func(s *ConfigurationUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *ConfigurationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConfigurationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConfigurationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConfigurationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
