// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api_server/ent/modeling"
	"api_server/ent/modelingdetails"
	"api_server/ent/modelingmodels"
	"api_server/ent/predicate"
	"api_server/ent/task"
	"api_server/ent/trial"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ModelingQuery is the builder for querying Modeling entities.
type ModelingQuery struct {
	config
	ctx                 *QueryContext
	order               []modeling.OrderOption
	inters              []Interceptor
	predicates          []predicate.Modeling
	withTask            *TaskQuery
	withModelingDetails *ModelingDetailsQuery
	withModelingModels  *ModelingModelsQuery
	withTrials          *TrialQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModelingQuery builder.
func (mq *ModelingQuery) Where(ps ...predicate.Modeling) *ModelingQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *ModelingQuery) Limit(limit int) *ModelingQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *ModelingQuery) Offset(offset int) *ModelingQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *ModelingQuery) Unique(unique bool) *ModelingQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *ModelingQuery) Order(o ...modeling.OrderOption) *ModelingQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryTask chains the current query on the "task" edge.
func (mq *ModelingQuery) QueryTask() *TaskQuery {
	query := (&TaskClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modeling.Table, modeling.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modeling.TaskTable, modeling.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModelingDetails chains the current query on the "modeling_details" edge.
func (mq *ModelingQuery) QueryModelingDetails() *ModelingDetailsQuery {
	query := (&ModelingDetailsClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modeling.Table, modeling.FieldID, selector),
			sqlgraph.To(modelingdetails.Table, modelingdetails.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, modeling.ModelingDetailsTable, modeling.ModelingDetailsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModelingModels chains the current query on the "modeling_models" edge.
func (mq *ModelingQuery) QueryModelingModels() *ModelingModelsQuery {
	query := (&ModelingModelsClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modeling.Table, modeling.FieldID, selector),
			sqlgraph.To(modelingmodels.Table, modelingmodels.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, modeling.ModelingModelsTable, modeling.ModelingModelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTrials chains the current query on the "trials" edge.
func (mq *ModelingQuery) QueryTrials() *TrialQuery {
	query := (&TrialClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modeling.Table, modeling.FieldID, selector),
			sqlgraph.To(trial.Table, trial.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, modeling.TrialsTable, modeling.TrialsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Modeling entity from the query.
// Returns a *NotFoundError when no Modeling was found.
func (mq *ModelingQuery) First(ctx context.Context) (*Modeling, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{modeling.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *ModelingQuery) FirstX(ctx context.Context) *Modeling {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Modeling ID from the query.
// Returns a *NotFoundError when no Modeling ID was found.
func (mq *ModelingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(1).IDs(setContextOp(ctx, mq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{modeling.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *ModelingQuery) FirstIDX(ctx context.Context) int {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Modeling entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Modeling entity is found.
// Returns a *NotFoundError when no Modeling entities are found.
func (mq *ModelingQuery) Only(ctx context.Context) (*Modeling, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{modeling.Label}
	default:
		return nil, &NotSingularError{modeling.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *ModelingQuery) OnlyX(ctx context.Context) *Modeling {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Modeling ID in the query.
// Returns a *NotSingularError when more than one Modeling ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *ModelingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(2).IDs(setContextOp(ctx, mq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{modeling.Label}
	default:
		err = &NotSingularError{modeling.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *ModelingQuery) OnlyIDX(ctx context.Context) int {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Modelings.
func (mq *ModelingQuery) All(ctx context.Context) ([]*Modeling, error) {
	ctx = setContextOp(ctx, mq.ctx, "All")
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Modeling, *ModelingQuery]()
	return withInterceptors[[]*Modeling](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *ModelingQuery) AllX(ctx context.Context) []*Modeling {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Modeling IDs.
func (mq *ModelingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mq.ctx.Unique == nil && mq.path != nil {
		mq.Unique(true)
	}
	ctx = setContextOp(ctx, mq.ctx, "IDs")
	if err = mq.Select(modeling.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *ModelingQuery) IDsX(ctx context.Context) []int {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *ModelingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, "Count")
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*ModelingQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *ModelingQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *ModelingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, "Exist")
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *ModelingQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModelingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *ModelingQuery) Clone() *ModelingQuery {
	if mq == nil {
		return nil
	}
	return &ModelingQuery{
		config:              mq.config,
		ctx:                 mq.ctx.Clone(),
		order:               append([]modeling.OrderOption{}, mq.order...),
		inters:              append([]Interceptor{}, mq.inters...),
		predicates:          append([]predicate.Modeling{}, mq.predicates...),
		withTask:            mq.withTask.Clone(),
		withModelingDetails: mq.withModelingDetails.Clone(),
		withModelingModels:  mq.withModelingModels.Clone(),
		withTrials:          mq.withTrials.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *ModelingQuery) WithTask(opts ...func(*TaskQuery)) *ModelingQuery {
	query := (&TaskClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withTask = query
	return mq
}

// WithModelingDetails tells the query-builder to eager-load the nodes that are connected to
// the "modeling_details" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *ModelingQuery) WithModelingDetails(opts ...func(*ModelingDetailsQuery)) *ModelingQuery {
	query := (&ModelingDetailsClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withModelingDetails = query
	return mq
}

// WithModelingModels tells the query-builder to eager-load the nodes that are connected to
// the "modeling_models" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *ModelingQuery) WithModelingModels(opts ...func(*ModelingModelsQuery)) *ModelingQuery {
	query := (&ModelingModelsClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withModelingModels = query
	return mq
}

// WithTrials tells the query-builder to eager-load the nodes that are connected to
// the "trials" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *ModelingQuery) WithTrials(opts ...func(*TrialQuery)) *ModelingQuery {
	query := (&TrialClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withTrials = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LocalID int `json:"local_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Modeling.Query().
//		GroupBy(modeling.FieldLocalID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *ModelingQuery) GroupBy(field string, fields ...string) *ModelingGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModelingGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = modeling.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LocalID int `json:"local_id,omitempty"`
//	}
//
//	client.Modeling.Query().
//		Select(modeling.FieldLocalID).
//		Scan(ctx, &v)
func (mq *ModelingQuery) Select(fields ...string) *ModelingSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &ModelingSelect{ModelingQuery: mq}
	sbuild.label = modeling.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModelingSelect configured with the given aggregations.
func (mq *ModelingQuery) Aggregate(fns ...AggregateFunc) *ModelingSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *ModelingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !modeling.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *ModelingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Modeling, error) {
	var (
		nodes       = []*Modeling{}
		_spec       = mq.querySpec()
		loadedTypes = [4]bool{
			mq.withTask != nil,
			mq.withModelingDetails != nil,
			mq.withModelingModels != nil,
			mq.withTrials != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Modeling).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Modeling{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(mq.modifiers) > 0 {
		_spec.Modifiers = mq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withTask; query != nil {
		if err := mq.loadTask(ctx, query, nodes, nil,
			func(n *Modeling, e *Task) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	if query := mq.withModelingDetails; query != nil {
		if err := mq.loadModelingDetails(ctx, query, nodes,
			func(n *Modeling) { n.Edges.ModelingDetails = []*ModelingDetails{} },
			func(n *Modeling, e *ModelingDetails) { n.Edges.ModelingDetails = append(n.Edges.ModelingDetails, e) }); err != nil {
			return nil, err
		}
	}
	if query := mq.withModelingModels; query != nil {
		if err := mq.loadModelingModels(ctx, query, nodes,
			func(n *Modeling) { n.Edges.ModelingModels = []*ModelingModels{} },
			func(n *Modeling, e *ModelingModels) { n.Edges.ModelingModels = append(n.Edges.ModelingModels, e) }); err != nil {
			return nil, err
		}
	}
	if query := mq.withTrials; query != nil {
		if err := mq.loadTrials(ctx, query, nodes,
			func(n *Modeling) { n.Edges.Trials = []*Trial{} },
			func(n *Modeling, e *Trial) { n.Edges.Trials = append(n.Edges.Trials, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *ModelingQuery) loadTask(ctx context.Context, query *TaskQuery, nodes []*Modeling, init func(*Modeling), assign func(*Modeling, *Task)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Modeling)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mq *ModelingQuery) loadModelingDetails(ctx context.Context, query *ModelingDetailsQuery, nodes []*Modeling, init func(*Modeling), assign func(*Modeling, *ModelingDetails)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Modeling)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(modelingdetails.FieldModelingID)
	}
	query.Where(predicate.ModelingDetails(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(modeling.ModelingDetailsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ModelingID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "modeling_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (mq *ModelingQuery) loadModelingModels(ctx context.Context, query *ModelingModelsQuery, nodes []*Modeling, init func(*Modeling), assign func(*Modeling, *ModelingModels)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Modeling)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(modelingmodels.FieldModelingID)
	}
	query.Where(predicate.ModelingModels(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(modeling.ModelingModelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ModelingID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "modeling_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (mq *ModelingQuery) loadTrials(ctx context.Context, query *TrialQuery, nodes []*Modeling, init func(*Modeling), assign func(*Modeling, *Trial)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Modeling)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(trial.FieldModelingID)
	}
	query.Where(predicate.Trial(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(modeling.TrialsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ModelingID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "modeling_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (mq *ModelingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	if len(mq.modifiers) > 0 {
		_spec.Modifiers = mq.modifiers
	}
	_spec.Node.Columns = mq.ctx.Fields
	if len(mq.ctx.Fields) > 0 {
		_spec.Unique = mq.ctx.Unique != nil && *mq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *ModelingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(modeling.Table, modeling.Columns, sqlgraph.NewFieldSpec(modeling.FieldID, field.TypeInt))
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modeling.FieldID)
		for i := range fields {
			if fields[i] != modeling.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mq.withTask != nil {
			_spec.Node.AddColumnOnce(modeling.FieldTaskID)
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *ModelingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(modeling.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = modeling.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range mq.modifiers {
		m(selector)
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mq *ModelingQuery) Modify(modifiers ...func(s *sql.Selector)) *ModelingSelect {
	mq.modifiers = append(mq.modifiers, modifiers...)
	return mq.Select()
}

// ModelingGroupBy is the group-by builder for Modeling entities.
type ModelingGroupBy struct {
	selector
	build *ModelingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *ModelingGroupBy) Aggregate(fns ...AggregateFunc) *ModelingGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *ModelingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, "GroupBy")
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelingQuery, *ModelingGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *ModelingGroupBy) sqlScan(ctx context.Context, root *ModelingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModelingSelect is the builder for selecting fields of Modeling entities.
type ModelingSelect struct {
	*ModelingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *ModelingSelect) Aggregate(fns ...AggregateFunc) *ModelingSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *ModelingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, "Select")
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelingQuery, *ModelingSelect](ctx, ms.ModelingQuery, ms, ms.inters, v)
}

func (ms *ModelingSelect) sqlScan(ctx context.Context, root *ModelingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ms *ModelingSelect) Modify(modifiers ...func(s *sql.Selector)) *ModelingSelect {
	ms.modifiers = append(ms.modifiers, modifiers...)
	return ms
}
