// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api_server/ent/modeling"
	"api_server/ent/modelingdetails"
	"api_server/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ModelingDetailsQuery is the builder for querying ModelingDetails entities.
type ModelingDetailsQuery struct {
	config
	ctx          *QueryContext
	order        []modelingdetails.OrderOption
	inters       []Interceptor
	predicates   []predicate.ModelingDetails
	withModeling *ModelingQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModelingDetailsQuery builder.
func (mdq *ModelingDetailsQuery) Where(ps ...predicate.ModelingDetails) *ModelingDetailsQuery {
	mdq.predicates = append(mdq.predicates, ps...)
	return mdq
}

// Limit the number of records to be returned by this query.
func (mdq *ModelingDetailsQuery) Limit(limit int) *ModelingDetailsQuery {
	mdq.ctx.Limit = &limit
	return mdq
}

// Offset to start from.
func (mdq *ModelingDetailsQuery) Offset(offset int) *ModelingDetailsQuery {
	mdq.ctx.Offset = &offset
	return mdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mdq *ModelingDetailsQuery) Unique(unique bool) *ModelingDetailsQuery {
	mdq.ctx.Unique = &unique
	return mdq
}

// Order specifies how the records should be ordered.
func (mdq *ModelingDetailsQuery) Order(o ...modelingdetails.OrderOption) *ModelingDetailsQuery {
	mdq.order = append(mdq.order, o...)
	return mdq
}

// QueryModeling chains the current query on the "modeling" edge.
func (mdq *ModelingDetailsQuery) QueryModeling() *ModelingQuery {
	query := (&ModelingClient{config: mdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modelingdetails.Table, modelingdetails.FieldID, selector),
			sqlgraph.To(modeling.Table, modeling.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modelingdetails.ModelingTable, modelingdetails.ModelingColumn),
		)
		fromU = sqlgraph.SetNeighbors(mdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ModelingDetails entity from the query.
// Returns a *NotFoundError when no ModelingDetails was found.
func (mdq *ModelingDetailsQuery) First(ctx context.Context) (*ModelingDetails, error) {
	nodes, err := mdq.Limit(1).All(setContextOp(ctx, mdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{modelingdetails.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) FirstX(ctx context.Context) *ModelingDetails {
	node, err := mdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModelingDetails ID from the query.
// Returns a *NotFoundError when no ModelingDetails ID was found.
func (mdq *ModelingDetailsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(1).IDs(setContextOp(ctx, mdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{modelingdetails.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) FirstIDX(ctx context.Context) int {
	id, err := mdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModelingDetails entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ModelingDetails entity is found.
// Returns a *NotFoundError when no ModelingDetails entities are found.
func (mdq *ModelingDetailsQuery) Only(ctx context.Context) (*ModelingDetails, error) {
	nodes, err := mdq.Limit(2).All(setContextOp(ctx, mdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{modelingdetails.Label}
	default:
		return nil, &NotSingularError{modelingdetails.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) OnlyX(ctx context.Context) *ModelingDetails {
	node, err := mdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModelingDetails ID in the query.
// Returns a *NotSingularError when more than one ModelingDetails ID is found.
// Returns a *NotFoundError when no entities are found.
func (mdq *ModelingDetailsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(2).IDs(setContextOp(ctx, mdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{modelingdetails.Label}
	default:
		err = &NotSingularError{modelingdetails.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) OnlyIDX(ctx context.Context) int {
	id, err := mdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModelingDetailsSlice.
func (mdq *ModelingDetailsQuery) All(ctx context.Context) ([]*ModelingDetails, error) {
	ctx = setContextOp(ctx, mdq.ctx, "All")
	if err := mdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ModelingDetails, *ModelingDetailsQuery]()
	return withInterceptors[[]*ModelingDetails](ctx, mdq, qr, mdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) AllX(ctx context.Context) []*ModelingDetails {
	nodes, err := mdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModelingDetails IDs.
func (mdq *ModelingDetailsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mdq.ctx.Unique == nil && mdq.path != nil {
		mdq.Unique(true)
	}
	ctx = setContextOp(ctx, mdq.ctx, "IDs")
	if err = mdq.Select(modelingdetails.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) IDsX(ctx context.Context) []int {
	ids, err := mdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mdq *ModelingDetailsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mdq.ctx, "Count")
	if err := mdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mdq, querierCount[*ModelingDetailsQuery](), mdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) CountX(ctx context.Context) int {
	count, err := mdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mdq *ModelingDetailsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mdq.ctx, "Exist")
	switch _, err := mdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mdq *ModelingDetailsQuery) ExistX(ctx context.Context) bool {
	exist, err := mdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModelingDetailsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mdq *ModelingDetailsQuery) Clone() *ModelingDetailsQuery {
	if mdq == nil {
		return nil
	}
	return &ModelingDetailsQuery{
		config:       mdq.config,
		ctx:          mdq.ctx.Clone(),
		order:        append([]modelingdetails.OrderOption{}, mdq.order...),
		inters:       append([]Interceptor{}, mdq.inters...),
		predicates:   append([]predicate.ModelingDetails{}, mdq.predicates...),
		withModeling: mdq.withModeling.Clone(),
		// clone intermediate query.
		sql:  mdq.sql.Clone(),
		path: mdq.path,
	}
}

// WithModeling tells the query-builder to eager-load the nodes that are connected to
// the "modeling" edge. The optional arguments are used to configure the query builder of the edge.
func (mdq *ModelingDetailsQuery) WithModeling(opts ...func(*ModelingQuery)) *ModelingDetailsQuery {
	query := (&ModelingClient{config: mdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mdq.withModeling = query
	return mdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ModelingID int `json:"modeling_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModelingDetails.Query().
//		GroupBy(modelingdetails.FieldModelingID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mdq *ModelingDetailsQuery) GroupBy(field string, fields ...string) *ModelingDetailsGroupBy {
	mdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModelingDetailsGroupBy{build: mdq}
	grbuild.flds = &mdq.ctx.Fields
	grbuild.label = modelingdetails.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ModelingID int `json:"modeling_id,omitempty"`
//	}
//
//	client.ModelingDetails.Query().
//		Select(modelingdetails.FieldModelingID).
//		Scan(ctx, &v)
func (mdq *ModelingDetailsQuery) Select(fields ...string) *ModelingDetailsSelect {
	mdq.ctx.Fields = append(mdq.ctx.Fields, fields...)
	sbuild := &ModelingDetailsSelect{ModelingDetailsQuery: mdq}
	sbuild.label = modelingdetails.Label
	sbuild.flds, sbuild.scan = &mdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModelingDetailsSelect configured with the given aggregations.
func (mdq *ModelingDetailsQuery) Aggregate(fns ...AggregateFunc) *ModelingDetailsSelect {
	return mdq.Select().Aggregate(fns...)
}

func (mdq *ModelingDetailsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mdq); err != nil {
				return err
			}
		}
	}
	for _, f := range mdq.ctx.Fields {
		if !modelingdetails.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mdq.path != nil {
		prev, err := mdq.path(ctx)
		if err != nil {
			return err
		}
		mdq.sql = prev
	}
	return nil
}

func (mdq *ModelingDetailsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ModelingDetails, error) {
	var (
		nodes       = []*ModelingDetails{}
		_spec       = mdq.querySpec()
		loadedTypes = [1]bool{
			mdq.withModeling != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ModelingDetails).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ModelingDetails{config: mdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(mdq.modifiers) > 0 {
		_spec.Modifiers = mdq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mdq.withModeling; query != nil {
		if err := mdq.loadModeling(ctx, query, nodes, nil,
			func(n *ModelingDetails, e *Modeling) { n.Edges.Modeling = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mdq *ModelingDetailsQuery) loadModeling(ctx context.Context, query *ModelingQuery, nodes []*ModelingDetails, init func(*ModelingDetails), assign func(*ModelingDetails, *Modeling)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ModelingDetails)
	for i := range nodes {
		fk := nodes[i].ModelingID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(modeling.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "modeling_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mdq *ModelingDetailsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mdq.querySpec()
	if len(mdq.modifiers) > 0 {
		_spec.Modifiers = mdq.modifiers
	}
	_spec.Node.Columns = mdq.ctx.Fields
	if len(mdq.ctx.Fields) > 0 {
		_spec.Unique = mdq.ctx.Unique != nil && *mdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mdq.driver, _spec)
}

func (mdq *ModelingDetailsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(modelingdetails.Table, modelingdetails.Columns, sqlgraph.NewFieldSpec(modelingdetails.FieldID, field.TypeInt))
	_spec.From = mdq.sql
	if unique := mdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mdq.path != nil {
		_spec.Unique = true
	}
	if fields := mdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelingdetails.FieldID)
		for i := range fields {
			if fields[i] != modelingdetails.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mdq.withModeling != nil {
			_spec.Node.AddColumnOnce(modelingdetails.FieldModelingID)
		}
	}
	if ps := mdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mdq *ModelingDetailsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mdq.driver.Dialect())
	t1 := builder.Table(modelingdetails.Table)
	columns := mdq.ctx.Fields
	if len(columns) == 0 {
		columns = modelingdetails.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mdq.sql != nil {
		selector = mdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mdq.ctx.Unique != nil && *mdq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range mdq.modifiers {
		m(selector)
	}
	for _, p := range mdq.predicates {
		p(selector)
	}
	for _, p := range mdq.order {
		p(selector)
	}
	if offset := mdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mdq *ModelingDetailsQuery) Modify(modifiers ...func(s *sql.Selector)) *ModelingDetailsSelect {
	mdq.modifiers = append(mdq.modifiers, modifiers...)
	return mdq.Select()
}

// ModelingDetailsGroupBy is the group-by builder for ModelingDetails entities.
type ModelingDetailsGroupBy struct {
	selector
	build *ModelingDetailsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mdgb *ModelingDetailsGroupBy) Aggregate(fns ...AggregateFunc) *ModelingDetailsGroupBy {
	mdgb.fns = append(mdgb.fns, fns...)
	return mdgb
}

// Scan applies the selector query and scans the result into the given value.
func (mdgb *ModelingDetailsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mdgb.build.ctx, "GroupBy")
	if err := mdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelingDetailsQuery, *ModelingDetailsGroupBy](ctx, mdgb.build, mdgb, mdgb.build.inters, v)
}

func (mdgb *ModelingDetailsGroupBy) sqlScan(ctx context.Context, root *ModelingDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mdgb.fns))
	for _, fn := range mdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mdgb.flds)+len(mdgb.fns))
		for _, f := range *mdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModelingDetailsSelect is the builder for selecting fields of ModelingDetails entities.
type ModelingDetailsSelect struct {
	*ModelingDetailsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mds *ModelingDetailsSelect) Aggregate(fns ...AggregateFunc) *ModelingDetailsSelect {
	mds.fns = append(mds.fns, fns...)
	return mds
}

// Scan applies the selector query and scans the result into the given value.
func (mds *ModelingDetailsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mds.ctx, "Select")
	if err := mds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelingDetailsQuery, *ModelingDetailsSelect](ctx, mds.ModelingDetailsQuery, mds, mds.inters, v)
}

func (mds *ModelingDetailsSelect) sqlScan(ctx context.Context, root *ModelingDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mds.fns))
	for _, fn := range mds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mds *ModelingDetailsSelect) Modify(modifiers ...func(s *sql.Selector)) *ModelingDetailsSelect {
	mds.modifiers = append(mds.modifiers, modifiers...)
	return mds
}
