// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api_server/ent/modeling"
	"api_server/ent/predicate"
	"api_server/ent/trial"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrialQuery is the builder for querying Trial entities.
type TrialQuery struct {
	config
	ctx          *QueryContext
	order        []trial.OrderOption
	inters       []Interceptor
	predicates   []predicate.Trial
	withModeling *ModelingQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrialQuery builder.
func (tq *TrialQuery) Where(ps ...predicate.Trial) *TrialQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TrialQuery) Limit(limit int) *TrialQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TrialQuery) Offset(offset int) *TrialQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TrialQuery) Unique(unique bool) *TrialQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TrialQuery) Order(o ...trial.OrderOption) *TrialQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryModeling chains the current query on the "modeling" edge.
func (tq *TrialQuery) QueryModeling() *ModelingQuery {
	query := (&ModelingClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(trial.Table, trial.FieldID, selector),
			sqlgraph.To(modeling.Table, modeling.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, trial.ModelingTable, trial.ModelingColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Trial entity from the query.
// Returns a *NotFoundError when no Trial was found.
func (tq *TrialQuery) First(ctx context.Context) (*Trial, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trial.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TrialQuery) FirstX(ctx context.Context) *Trial {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Trial ID from the query.
// Returns a *NotFoundError when no Trial ID was found.
func (tq *TrialQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trial.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TrialQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Trial entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Trial entity is found.
// Returns a *NotFoundError when no Trial entities are found.
func (tq *TrialQuery) Only(ctx context.Context) (*Trial, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trial.Label}
	default:
		return nil, &NotSingularError{trial.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TrialQuery) OnlyX(ctx context.Context) *Trial {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Trial ID in the query.
// Returns a *NotSingularError when more than one Trial ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TrialQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trial.Label}
	default:
		err = &NotSingularError{trial.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TrialQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Trials.
func (tq *TrialQuery) All(ctx context.Context) ([]*Trial, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryAll)
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Trial, *TrialQuery]()
	return withInterceptors[[]*Trial](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TrialQuery) AllX(ctx context.Context) []*Trial {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Trial IDs.
func (tq *TrialQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryIDs)
	if err = tq.Select(trial.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TrialQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TrialQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryCount)
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TrialQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TrialQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TrialQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryExist)
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TrialQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrialQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TrialQuery) Clone() *TrialQuery {
	if tq == nil {
		return nil
	}
	return &TrialQuery{
		config:       tq.config,
		ctx:          tq.ctx.Clone(),
		order:        append([]trial.OrderOption{}, tq.order...),
		inters:       append([]Interceptor{}, tq.inters...),
		predicates:   append([]predicate.Trial{}, tq.predicates...),
		withModeling: tq.withModeling.Clone(),
		// clone intermediate query.
		sql:       tq.sql.Clone(),
		path:      tq.path,
		modifiers: append([]func(*sql.Selector){}, tq.modifiers...),
	}
}

// WithModeling tells the query-builder to eager-load the nodes that are connected to
// the "modeling" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TrialQuery) WithModeling(opts ...func(*ModelingQuery)) *TrialQuery {
	query := (&ModelingClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withModeling = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ModelingID int `json:"modeling_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Trial.Query().
//		GroupBy(trial.FieldModelingID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TrialQuery) GroupBy(field string, fields ...string) *TrialGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrialGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = trial.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ModelingID int `json:"modeling_id,omitempty"`
//	}
//
//	client.Trial.Query().
//		Select(trial.FieldModelingID).
//		Scan(ctx, &v)
func (tq *TrialQuery) Select(fields ...string) *TrialSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TrialSelect{TrialQuery: tq}
	sbuild.label = trial.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrialSelect configured with the given aggregations.
func (tq *TrialQuery) Aggregate(fns ...AggregateFunc) *TrialSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TrialQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !trial.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TrialQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Trial, error) {
	var (
		nodes       = []*Trial{}
		_spec       = tq.querySpec()
		loadedTypes = [1]bool{
			tq.withModeling != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Trial).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Trial{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withModeling; query != nil {
		if err := tq.loadModeling(ctx, query, nodes, nil,
			func(n *Trial, e *Modeling) { n.Edges.Modeling = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TrialQuery) loadModeling(ctx context.Context, query *ModelingQuery, nodes []*Trial, init func(*Trial), assign func(*Trial, *Modeling)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Trial)
	for i := range nodes {
		fk := nodes[i].ModelingID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(modeling.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "modeling_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tq *TrialQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TrialQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(trial.Table, trial.Columns, sqlgraph.NewFieldSpec(trial.FieldID, field.TypeInt))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trial.FieldID)
		for i := range fields {
			if fields[i] != trial.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tq.withModeling != nil {
			_spec.Node.AddColumnOnce(trial.FieldModelingID)
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TrialQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(trial.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = trial.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tq.modifiers {
		m(selector)
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tq *TrialQuery) Modify(modifiers ...func(s *sql.Selector)) *TrialSelect {
	tq.modifiers = append(tq.modifiers, modifiers...)
	return tq.Select()
}

// TrialGroupBy is the group-by builder for Trial entities.
type TrialGroupBy struct {
	selector
	build *TrialQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TrialGroupBy) Aggregate(fns ...AggregateFunc) *TrialGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TrialGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, ent.OpQueryGroupBy)
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrialQuery, *TrialGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TrialGroupBy) sqlScan(ctx context.Context, root *TrialQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrialSelect is the builder for selecting fields of Trial entities.
type TrialSelect struct {
	*TrialQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TrialSelect) Aggregate(fns ...AggregateFunc) *TrialSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TrialSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, ent.OpQuerySelect)
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrialQuery, *TrialSelect](ctx, ts.TrialQuery, ts, ts.inters, v)
}

func (ts *TrialSelect) sqlScan(ctx context.Context, root *TrialQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ts *TrialSelect) Modify(modifiers ...func(s *sql.Selector)) *TrialSelect {
	ts.modifiers = append(ts.modifiers, modifiers...)
	return ts
}
