// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api_server/ent/predicate"
	"api_server/ent/trialdetails"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrialDetailsDelete is the builder for deleting a TrialDetails entity.
type TrialDetailsDelete struct {
	config
	hooks    []Hook
	mutation *TrialDetailsMutation
}

// Where appends a list predicates to the TrialDetailsDelete builder.
func (tdd *TrialDetailsDelete) Where(ps ...predicate.TrialDetails) *TrialDetailsDelete {
	tdd.mutation.Where(ps...)
	return tdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tdd *TrialDetailsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tdd.sqlExec, tdd.mutation, tdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tdd *TrialDetailsDelete) ExecX(ctx context.Context) int {
	n, err := tdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tdd *TrialDetailsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(trialdetails.Table, sqlgraph.NewFieldSpec(trialdetails.FieldID, field.TypeInt))
	if ps := tdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tdd.mutation.done = true
	return affected, err
}

// TrialDetailsDeleteOne is the builder for deleting a single TrialDetails entity.
type TrialDetailsDeleteOne struct {
	tdd *TrialDetailsDelete
}

// Where appends a list predicates to the TrialDetailsDelete builder.
func (tddo *TrialDetailsDeleteOne) Where(ps ...predicate.TrialDetails) *TrialDetailsDeleteOne {
	tddo.tdd.mutation.Where(ps...)
	return tddo
}

// Exec executes the deletion query.
func (tddo *TrialDetailsDeleteOne) Exec(ctx context.Context) error {
	n, err := tddo.tdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trialdetails.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tddo *TrialDetailsDeleteOne) ExecX(ctx context.Context) {
	if err := tddo.Exec(ctx); err != nil {
		panic(err)
	}
}
