// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api_server/ent/predicate"
	"api_server/ent/trialdetails"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrialDetailsQuery is the builder for querying TrialDetails entities.
type TrialDetailsQuery struct {
	config
	ctx        *QueryContext
	order      []trialdetails.OrderOption
	inters     []Interceptor
	predicates []predicate.TrialDetails
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrialDetailsQuery builder.
func (tdq *TrialDetailsQuery) Where(ps ...predicate.TrialDetails) *TrialDetailsQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit the number of records to be returned by this query.
func (tdq *TrialDetailsQuery) Limit(limit int) *TrialDetailsQuery {
	tdq.ctx.Limit = &limit
	return tdq
}

// Offset to start from.
func (tdq *TrialDetailsQuery) Offset(offset int) *TrialDetailsQuery {
	tdq.ctx.Offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *TrialDetailsQuery) Unique(unique bool) *TrialDetailsQuery {
	tdq.ctx.Unique = &unique
	return tdq
}

// Order specifies how the records should be ordered.
func (tdq *TrialDetailsQuery) Order(o ...trialdetails.OrderOption) *TrialDetailsQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// First returns the first TrialDetails entity from the query.
// Returns a *NotFoundError when no TrialDetails was found.
func (tdq *TrialDetailsQuery) First(ctx context.Context) (*TrialDetails, error) {
	nodes, err := tdq.Limit(1).All(setContextOp(ctx, tdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trialdetails.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TrialDetailsQuery) FirstX(ctx context.Context) *TrialDetails {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TrialDetails ID from the query.
// Returns a *NotFoundError when no TrialDetails ID was found.
func (tdq *TrialDetailsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(1).IDs(setContextOp(ctx, tdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trialdetails.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *TrialDetailsQuery) FirstIDX(ctx context.Context) int {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TrialDetails entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TrialDetails entity is found.
// Returns a *NotFoundError when no TrialDetails entities are found.
func (tdq *TrialDetailsQuery) Only(ctx context.Context) (*TrialDetails, error) {
	nodes, err := tdq.Limit(2).All(setContextOp(ctx, tdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trialdetails.Label}
	default:
		return nil, &NotSingularError{trialdetails.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TrialDetailsQuery) OnlyX(ctx context.Context) *TrialDetails {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TrialDetails ID in the query.
// Returns a *NotSingularError when more than one TrialDetails ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *TrialDetailsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(2).IDs(setContextOp(ctx, tdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trialdetails.Label}
	default:
		err = &NotSingularError{trialdetails.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TrialDetailsQuery) OnlyIDX(ctx context.Context) int {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TrialDetailsSlice.
func (tdq *TrialDetailsQuery) All(ctx context.Context) ([]*TrialDetails, error) {
	ctx = setContextOp(ctx, tdq.ctx, "All")
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TrialDetails, *TrialDetailsQuery]()
	return withInterceptors[[]*TrialDetails](ctx, tdq, qr, tdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TrialDetailsQuery) AllX(ctx context.Context) []*TrialDetails {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TrialDetails IDs.
func (tdq *TrialDetailsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tdq.ctx.Unique == nil && tdq.path != nil {
		tdq.Unique(true)
	}
	ctx = setContextOp(ctx, tdq.ctx, "IDs")
	if err = tdq.Select(trialdetails.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TrialDetailsQuery) IDsX(ctx context.Context) []int {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TrialDetailsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Count")
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tdq, querierCount[*TrialDetailsQuery](), tdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TrialDetailsQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TrialDetailsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Exist")
	switch _, err := tdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TrialDetailsQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrialDetailsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TrialDetailsQuery) Clone() *TrialDetailsQuery {
	if tdq == nil {
		return nil
	}
	return &TrialDetailsQuery{
		config:     tdq.config,
		ctx:        tdq.ctx.Clone(),
		order:      append([]trialdetails.OrderOption{}, tdq.order...),
		inters:     append([]Interceptor{}, tdq.inters...),
		predicates: append([]predicate.TrialDetails{}, tdq.predicates...),
		// clone intermediate query.
		sql:  tdq.sql.Clone(),
		path: tdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TrialUUID string `json:"trial_uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TrialDetails.Query().
//		GroupBy(trialdetails.FieldTrialUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tdq *TrialDetailsQuery) GroupBy(field string, fields ...string) *TrialDetailsGroupBy {
	tdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrialDetailsGroupBy{build: tdq}
	grbuild.flds = &tdq.ctx.Fields
	grbuild.label = trialdetails.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TrialUUID string `json:"trial_uuid,omitempty"`
//	}
//
//	client.TrialDetails.Query().
//		Select(trialdetails.FieldTrialUUID).
//		Scan(ctx, &v)
func (tdq *TrialDetailsQuery) Select(fields ...string) *TrialDetailsSelect {
	tdq.ctx.Fields = append(tdq.ctx.Fields, fields...)
	sbuild := &TrialDetailsSelect{TrialDetailsQuery: tdq}
	sbuild.label = trialdetails.Label
	sbuild.flds, sbuild.scan = &tdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrialDetailsSelect configured with the given aggregations.
func (tdq *TrialDetailsQuery) Aggregate(fns ...AggregateFunc) *TrialDetailsSelect {
	return tdq.Select().Aggregate(fns...)
}

func (tdq *TrialDetailsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tdq); err != nil {
				return err
			}
		}
	}
	for _, f := range tdq.ctx.Fields {
		if !trialdetails.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TrialDetailsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TrialDetails, error) {
	var (
		nodes = []*TrialDetails{}
		_spec = tdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TrialDetails).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TrialDetails{config: tdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(tdq.modifiers) > 0 {
		_spec.Modifiers = tdq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tdq *TrialDetailsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	if len(tdq.modifiers) > 0 {
		_spec.Modifiers = tdq.modifiers
	}
	_spec.Node.Columns = tdq.ctx.Fields
	if len(tdq.ctx.Fields) > 0 {
		_spec.Unique = tdq.ctx.Unique != nil && *tdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TrialDetailsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(trialdetails.Table, trialdetails.Columns, sqlgraph.NewFieldSpec(trialdetails.FieldID, field.TypeInt))
	_spec.From = tdq.sql
	if unique := tdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tdq.path != nil {
		_spec.Unique = true
	}
	if fields := tdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trialdetails.FieldID)
		for i := range fields {
			if fields[i] != trialdetails.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TrialDetailsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(trialdetails.Table)
	columns := tdq.ctx.Fields
	if len(columns) == 0 {
		columns = trialdetails.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.ctx.Unique != nil && *tdq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tdq.modifiers {
		m(selector)
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tdq *TrialDetailsQuery) Modify(modifiers ...func(s *sql.Selector)) *TrialDetailsSelect {
	tdq.modifiers = append(tdq.modifiers, modifiers...)
	return tdq.Select()
}

// TrialDetailsGroupBy is the group-by builder for TrialDetails entities.
type TrialDetailsGroupBy struct {
	selector
	build *TrialDetailsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TrialDetailsGroupBy) Aggregate(fns ...AggregateFunc) *TrialDetailsGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the selector query and scans the result into the given value.
func (tdgb *TrialDetailsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tdgb.build.ctx, "GroupBy")
	if err := tdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrialDetailsQuery, *TrialDetailsGroupBy](ctx, tdgb.build, tdgb, tdgb.build.inters, v)
}

func (tdgb *TrialDetailsGroupBy) sqlScan(ctx context.Context, root *TrialDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tdgb.flds)+len(tdgb.fns))
		for _, f := range *tdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrialDetailsSelect is the builder for selecting fields of TrialDetails entities.
type TrialDetailsSelect struct {
	*TrialDetailsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tds *TrialDetailsSelect) Aggregate(fns ...AggregateFunc) *TrialDetailsSelect {
	tds.fns = append(tds.fns, fns...)
	return tds
}

// Scan applies the selector query and scans the result into the given value.
func (tds *TrialDetailsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tds.ctx, "Select")
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrialDetailsQuery, *TrialDetailsSelect](ctx, tds.TrialDetailsQuery, tds, tds.inters, v)
}

func (tds *TrialDetailsSelect) sqlScan(ctx context.Context, root *TrialDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tds.fns))
	for _, fn := range tds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tds *TrialDetailsSelect) Modify(modifiers ...func(s *sql.Selector)) *TrialDetailsSelect {
	tds.modifiers = append(tds.modifiers, modifiers...)
	return tds
}
