// Code generated by ent, DO NOT EDIT.

package hyperparamshistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the hyperparamshistory type in the database.
	Label = "hyper_params_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrialID holds the string denoting the trial_id field in the database.
	FieldTrialID = "trial_id"
	// FieldTrialUUID holds the string denoting the trial_uuid field in the database.
	FieldTrialUUID = "trial_uuid"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldModelNum holds the string denoting the model_num field in the database.
	FieldModelNum = "model_num"
	// FieldParams holds the string denoting the params field in the database.
	FieldParams = "params"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the hyperparamshistory in the database.
	Table = "hyper_params_history"
)

// Columns holds all SQL columns for hyperparamshistory fields.
var Columns = []string{
	FieldID,
	FieldTrialID,
	FieldTrialUUID,
	FieldModel,
	FieldModelNum,
	FieldParams,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTrialID holds the default value on creation for the "trial_id" field.
	DefaultTrialID int
	// DefaultTrialUUID holds the default value on creation for the "trial_uuid" field.
	DefaultTrialUUID string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultModelNum holds the default value on creation for the "model_num" field.
	DefaultModelNum int
	// DefaultParams holds the default value on creation for the "params" field.
	DefaultParams string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the HyperParamsHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrialID orders the results by the trial_id field.
func ByTrialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrialID, opts...).ToFunc()
}

// ByTrialUUID orders the results by the trial_uuid field.
func ByTrialUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrialUUID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByModelNum orders the results by the model_num field.
func ByModelNum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelNum, opts...).ToFunc()
}

// ByParams orders the results by the params field.
func ByParams(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParams, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
